import {
  Plug,
  Bridge,
  Handshake,
  Truck,
  Trash,
  Recycle,
  Globe,
  MapPin,
  Phone,
  Envelope,
  Clock,
  Gauge,
  Gear,
  ShieldCheck,
  BadgeCheck,
  Drop,
  Waves,
  Lightning,
  GasPump,
  Users,
  Briefcase,
  ArrowUpRight,
  CaretLeft,
  CaretRight,
  X,
  UploadSimple,
  CheckCircle,
  Leaf,
  Factory,
  Buildings,
  RoadHorizon,
  Broom,
  Database,
  IdentificationCard,
  WarningCircle,
  Info,
} from '@phosphor-icons/react';

export const CMS_ICON_KEYS = [
  'plug',
  'bridge',
  'handshake',
  'truck',
  'trash',
  'recycle',
  'globe',
  'map-pin',
  'phone',
  'envelope',
  'clock',
  'gauge',
  'gear',
  'shield-check',
  'badge-check',
  'drop',
  'waves',
  'zap',
  'fuel',
  'settings',
  'users',
  'briefcase',
  'arrow-up-right',
  'caret-left',
  'caret-right',
  'x',
  'upload-simple',
  'check-circle',
  'leaf',
  'factory',
  'buildings',
  'road-horizon',
  'broom',
  'database',
  'identification-card',
  'warning-circle',
  'info',
] as const;

export type CMSIconKey = (typeof CMS_ICON_KEYS)[number];

const ICON_MAP = {
  plug: Plug,
  bridge: Bridge,
  handshake: Handshake,
  truck: Truck,
  trash: Trash,
  recycle: Recycle,
  globe: Globe,
  'map-pin': MapPin,
  phone: Phone,
  envelope: Envelope,
  clock: Clock,
  gauge: Gauge,
  gear: Gear,
  'shield-check': ShieldCheck,
  'badge-check': BadgeCheck,
  drop: Drop,
  waves: Waves,
  zap: Lightning,
  fuel: GasPump,
  settings: Gear,
  users: Users,
  briefcase: Briefcase,
  'arrow-up-right': ArrowUpRight,
  'caret-left': CaretLeft,
  'caret-right': CaretRight,
  x: X,
  'upload-simple': UploadSimple,
  'check-circle': CheckCircle,
  leaf: Leaf,
  factory: Factory,
  buildings: Buildings,
  'road-horizon': RoadHorizon,
  broom: Broom,
  database: Database,
  'identification-card': IdentificationCard,
  'warning-circle': WarningCircle,
  info: Info,
} satisfies Record<CMSIconKey, React.ComponentType<any>>;

export function normalizeIconKey(icon?: string | null): string {
  return String(icon || '')
    .trim()
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/_/g, '-');
}

export function getCMSIcon(icon?: string | null) {
  const key = normalizeIconKey(icon);

  return ICON_MAP[key as CMSIconKey] || Gear;
}